# v2 syntax
version: "2"

services:
  node:
    container_name: republica-node
    image: "node:8"
    user: "node"
    working_dir: "/var/www/app"
    volumes:
      - .:/var/www/app
    ports:
      - "3333:3333"
    command: "npm start"
